// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
import { createClient } from "npm:@supabase/supabase-js@^2.94.1";
var list_services_default = defineTool({
  name: "list_services",
  title: "List services",
  description: "List active marketing/advertising services offered by \u0627\u0628\u0648\u0637\u0644\u0627\u0644 \u0644\u0644\u062F\u0639\u0627\u064A\u0629 \u0648\u0627\u0644\u0625\u0639\u0644\u0627\u0646 \u0648\u0627\u0644\u062A\u0633\u0648\u064A\u0642 \u0627\u0644\u0625\u0644\u0643\u062A\u0631\u0648\u0646\u064A.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Max services to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY);
    const { data, error } = await supabase.from("services").select("id,name,description,category,price,icon,is_active").eq("is_active", true).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { services: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-packages.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.94.1";
var list_packages_default = defineTool2({
  name: "list_packages",
  title: "List packages",
  description: "List active promotional packages (Gold, Diamond, Silver) with pricing and features.",
  inputSchema: {
    type: z2.string().optional().describe("Filter by package type (e.g. 'gold', 'diamond', 'silver').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ type }) => {
    const supabase = createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY);
    let query = supabase.from("packages").select("id,name,type,description,features,price,discount_percent,is_active").eq("is_active", true).order("sort_order");
    if (type) query = query.eq("type", type);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { packages: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-ai-tools.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.94.1";
var list_ai_tools_default = defineTool3({
  name: "list_ai_tools",
  title: "List AI tools",
  description: "List active AI tools and models curated on \u0627\u0628\u0648\u0637\u0644\u0627\u0644 \u0644\u0644\u062F\u0639\u0627\u064A\u0629 \u0648\u0627\u0644\u0625\u0639\u0644\u0627\u0646 \u0648\u0627\u0644\u062A\u0633\u0648\u064A\u0642 \u0627\u0644\u0625\u0644\u0643\u062A\u0631\u0648\u0646\u064A.",
  inputSchema: {
    category: z3.string().optional().describe("Optional category filter (chat, image, video, audio, text, code, other)."),
    featured_only: z3.boolean().optional().describe("If true, return only featured tools.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, featured_only }) => {
    const supabase = createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY);
    let query = supabase.from("ai_tools").select("id,name,description,category,tool_url,is_featured,is_active,sort_order").eq("is_active", true).order("sort_order");
    if (category) query = query.eq("category", category);
    if (featured_only) query = query.eq("is_featured", true);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { tools: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-news.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.4.3";
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.94.1";
var list_news_default = defineTool4({
  name: "list_news",
  title: "List news ticker items",
  description: "List active news ticker announcements published on \u0627\u0628\u0648\u0637\u0644\u0627\u0644 \u0644\u0644\u062F\u0639\u0627\u064A\u0629 \u0648\u0627\u0644\u0625\u0639\u0644\u0627\u0646 \u0648\u0627\u0644\u062A\u0633\u0648\u064A\u0642 \u0627\u0644\u0625\u0644\u0643\u062A\u0631\u0648\u0646\u064A.",
  inputSchema: {
    limit: z4.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY);
    const { data, error } = await supabase.from("news_items").select("id,content,sort_order,created_at").eq("is_active", true).order("sort_order").limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { news: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "abotalal-platform-mcp",
  title: "\u0627\u0628\u0648\u0637\u0644\u0627\u0644 \u0644\u0644\u062F\u0639\u0627\u064A\u0629 \u0648\u0627\u0644\u0625\u0639\u0644\u0627\u0646 \u0648\u0627\u0644\u062A\u0633\u0648\u064A\u0642 \u0627\u0644\u0625\u0644\u0643\u062A\u0631\u0648\u0646\u064A MCP",
  version: "0.1.0",
  instructions: "Public catalog of \u0627\u0628\u0648\u0637\u0644\u0627\u0644 \u0644\u0644\u062F\u0639\u0627\u064A\u0629 \u0648\u0627\u0644\u0625\u0639\u0644\u0627\u0646 \u0648\u0627\u0644\u062A\u0633\u0648\u064A\u0642 \u0627\u0644\u0625\u0644\u0643\u062A\u0631\u0648\u0646\u064A (Abotalal Advertising and Digital Marketing): marketing/advertising services, promotional packages, curated AI tools, and news ticker announcements. Use these read-only tools to answer questions about what the platform offers.",
  tools: [list_services_default, list_packages_default, list_ai_tools_default, list_news_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
